// nav list component
export const navListItems = [
  {
    label: "Home",
    location: "/",
  },
  {
    label: "About",
    location: "/about",
  },
  {
    label: "Find Donor",
    location: "/find-donor",
  },
  {
    label: "Donate",
    location: "/donate",
  },
  {
    label: "Get Help",
    location: "/get-help",
  },
];

export const districts = [
  { value: "Abbottabad" },
  { value: "Astore" },
  { value: "Attock" },
  { value: "Awaran" },
  { value: "Badin" },
  { value: "Bagh" },
  { value: "Bahawalnagar" },
  { value: "Bahawalpur" },
  { value: "Bajaur" },
  { value: "Bannu" },
  { value: "Barkhan" },
  { value: "Bhimber" },
  { value: "Buner" },
  { value: "Chagai" },
  { value: "Chakwal" },
  { value: "Charsadda" },
  { value: "Chiniot" },
  { value: "Dadu" },
  { value: "Darel" },
  { value: "Dera Bugti" },
  { value: "Dera Ghazi Khan" },
  { value: "Dera Ismail Khan" },
  { value: "Diamer" },
  { value: "Duki" },
  { value: "Faisalabad" },
  { value: "Ghanche" },
  { value: "Ghizer" },
  { value: "Ghotki" },
  { value: "Gilgit" },
  { value: "Gujranwala" },
  { value: "Gujrat" },
  { value: "Gupis Yasin" },
  { value: "Gwadar" },
  { value: "Hafizabad" },
  { value: "Hangu" },
  { value: "Haripur" },
  { value: "Harnai" },
  { value: "Hattian" },
  { value: "Haveli" },
  { value: "Hunza" },
  { value: "Hyderabad" },
  { value: "Islamabad" },
  { value: "Jacobabad" },
  { value: "Jafarabad" },
  { value: "Jamshoro" },
  { value: "Jhal Magsi" },
  { value: "Jhang" },
  { value: "Jhelum" },
  { value: "Kachhi" },
  { value: "Kalat" },
  { value: "Karachi Central" },
  { value: "Karachi East" },
  { value: "Karachi South" },
  { value: "Karachi West" },
  { value: "Karak" },
  { value: "Kashmore" },
  { value: "Kasur" },
  { value: "Kech" },
  { value: "Khairpur" },
  { value: "Khanewal" },
  { value: "Kharan" },
  { value: "Kharmang" },
  { value: "Khushab" },
  { value: "Khuzdar" },
  { value: "Khyber" },
  { value: "Killa Abdullah" },
  { value: "Kohat" },
  { value: "Kohlu" },
  { value: "Kolai Pallas" },
  { value: "Korangi" },
  { value: "Kotli" },
  { value: "Kurram" },
  { value: "Lahore" },
  { value: "Lakki Marwat" },
  { value: "Larkana" },
  { value: "Lasbela" },
  { value: "Layyah" },
  { value: "Loralai" },
  { value: "Lower Chitral" },
  { value: "Lower Dir" },
  { value: "Lower Kohistan" },
  { value: "Malakand" },
  { value: "Malir" },
  { value: "Mandi Bahauddin" },
  { value: "Bhimber" },
  { value: "Buner" },
  { value: "Chagai" },
  { value: "Chakwal" },
  { value: "Charsadda" },
  { value: "Chiniot" },
  { value: "Dadu" },
  { value: "Darel" },
  { value: "Dera Bugti" },
  { value: "Dera Ghazi Khan" },
  { value: "Dera Ismail Khan" },
  { value: "Diamer" },
  { value: "Duki" },
  { value: "Faisalabad" },
  { value: "Ghanche" },
  { value: "Ghizer" },
  { value: "Ghotki" },
  { value: "Gilgit" },
  { value: "Gujranwala" },
  { value: "Gujrat" },
  { value: "Gupis Yasin" },
  { value: "Gwadar" },
  { value: "Hafizabad" },
  { value: "Hangu" },
  { value: "Haripur" },
  { value: "Harnai" },
  { value: "Hattian" },
  { value: "Haveli" },
  { value: "Hunza" },
  { value: "Hyderabad" },
  { value: "Islamabad" },
  { value: "Jacobabad" },
  { value: "Jafarabad" },
  { value: "Jamshoro" },
  { value: "Jhal Magsi" },
  { value: "Jhang" },
  { value: "Jhelum" },
  { value: "Kachhi" },
  { value: "Kalat" },
  { value: "Karachi Central" },
  { value: "Karachi East" },
  { value: "Karachi South" },
  { value: "Karachi West" },
  { value: "Karak" },
  { value: "Kashmore" },
  { value: "Kasur" },
  { value: "Kech" },
  { value: "Khairpur" },
  { value: "Khanewal" },
  { value: "Kharan" },
  { value: "Kharmang" },
  { value: "Khushab" },
  { value: "Khuzdar" },
  { value: "Khyber" },
  { value: "Killa Abdullah" },
  { value: "Kohat" },
  { value: "Kohlu" },
  { value: "Kolai Pallas" },
  { value: "Korangi" },
  { value: "Kotli" },
  { value: "Kurram" },
  { value: "Lahore" },
  { value: "Lakki Marwat" },
  { value: "Larkana" },
  { value: "Lasbela" },
  { value: "Layyah" },
  { value: "Loralai" },
  { value: "Lower Chitral" },
  { value: "Lower Dir" },
  { value: "Lower Kohistan" },
  { value: "Malakand" },
  { value: "Malir" },
  { value: "Mandi Bahauddin" },
  { value: "Mansehra" },
  { value: "Mardan" },
  { value: "Mastung" },
  { value: "Matiari" },
  { value: "Mianwali" },
  { value: "Mirpur Khas" },
  { value: "Mirpur" },
  { value: "Mohmand" },
  { value: "Multan" },
  { value: "Musakhel" },
  { value: "Muzaffarabad" },
  { value: "Muzaffargarh" },
  { value: "Nagar" },
  { value: "Nankana Sahib" },
  { value: "Narowal" },
  { value: "Naseerabad" },
  { value: "Naushahro Firoze" },
  { value: "Neelum" },
  { value: "North Waziristan" },
  { value: "Nowshera" },
  { value: "Nushki" },
  { value: "Okara" },
  { value: "Orakzai" },
  { value: "Pakpattan" },
  { value: "Panjgur" },
  { value: "Peshawar" },
  { value: "Pishin" },
  { value: "Poonch" },
  { value: "Qambar Shahdadkot" },
  { value: "Qilla Saifullah" },
  { value: "Quetta" },
  { value: "Rahim Yar Khan" },
  { value: "Rajanpur" },
  { value: "Rawalpindi" },
  { value: "Roundu" },
  { value: "Sahiwal" },
  { value: "Sanghar" },
  { value: "Sargodha" },
  { value: "Shaheed Benazirabad" },
  { value: "Shaheed Sikandarabad" },
  { value: "Shangla" },
  { value: "Sheikhupura" },
  { value: "Sherani" },
  { value: "Shigar" },
  { value: "Shikarpur" },
  { value: "Sialkot" },
  { value: "Sibi" },
  { value: "Skardu" },
  { value: "Sohbatpur" },
  { value: "South Waziristan" },
  { value: "Sudhnutti" },
  { value: "Sujawal" },
  { value: "Sukkur" },
  { value: "Swabi" },
  { value: "Swat" },
  { value: "Tando Allahyar" },
  { value: "Tando Muhammad Khan" },
  { value: "Tangir" },
  { value: "Tank" },
  { value: "Tharparkar" },
  { value: "Thatta" },
  { value: "Toba Tek Singh" },
  { value: "Tor Ghar" },
  { value: "Umerkot" },
  { value: "Upper Chitral" },
  { value: "Upper Dir" },
  { value: "Upper Kohistan" },
  { value: "Vehari" },
  { value: "Washuk" },
  { value: "Zhob" },
  { value: "Ziarat" },
];
