// nav list component
export const navListItems = [
  {
    label: "Home",
    location: "/",
  },
  {
    label: "About",
    location: "/about",
  },
  {
    label: "Find Donor",
    location: "/find-donor",
  },
  {
    label: "Donate",
    location: "/donate",
  },
  {
    label: "Get Help",
    location: "/get-help",
  },
  {
    label: "Login",
    location: "/donor/login",
  },
];

export const districts = [
  { value: "Abbottabad" },
  { value: "Astore" },
  { value: "Attock" },
  { value: "Awaran" },
  { value: "Badin" },
  { value: "Bagh" },
  { value: "Bahawalnagar" },
  { value: "Bahawalpur" },
  { value: "Bajaur" },
  { value: "Bannu" },
  { value: "Barkhan" },
  { value: "Bhimber" },
  { value: "Buner" },
  { value: "Chagai" },
  { value: "Chakwal" },
  { value: "Charsadda" },
  { value: "Chiniot" },
  { value: "Dadu" },
  { value: "Darel" },
  { value: "Dera Bugti" },
  { value: "Dera Ghazi Khan" },
  { value: "Dera Ismail Khan" },
  { value: "Diamer" },
  { value: "Duki" },
  { value: "Faisalabad" },
  { value: "Ghanche" },
  { value: "Ghizer" },
  { value: "Ghotki" },
  { value: "Gilgit" },
  { value: "Gujranwala" },
  { value: "Gujrat" },
  { value: "Gupis Yasin" },
  { value: "Gwadar" },
  { value: "Hafizabad" },
  { value: "Hangu" },
  { value: "Haripur" },
  { value: "Harnai" },
  { value: "Hattian" },
  { value: "Haveli" },
  { value: "Hunza" },
  { value: "Hyderabad" },
  { value: "Islamabad" },
  { value: "Jacobabad" },
  { value: "Jafarabad" },
  { value: "Jamshoro" },
  { value: "Jhal Magsi" },
  { value: "Jhang" },
  { value: "Jhelum" },
  { value: "Kachhi" },
  { value: "Kalat" },
  { value: "Karachi Central" },
  { value: "Karachi East" },
  { value: "Karachi South" },
  { value: "Karachi West" },
  { value: "Karak" },
  { value: "Kashmore" },
  { value: "Kasur" },
  { value: "Kech" },
  { value: "Khairpur" },
  { value: "Khanewal" },
  { value: "Kharan" },
  { value: "Kharmang" },
  { value: "Khushab" },
  { value: "Khuzdar" },
  { value: "Khyber" },
  { value: "Killa Abdullah" },
  { value: "Kohat" },
  { value: "Kohlu" },
  { value: "Kolai Pallas" },
  { value: "Korangi" },
  { value: "Kotli" },
  { value: "Kurram" },
  { value: "Lahore" },
  { value: "Lakki Marwat" },
  { value: "Larkana" },
  { value: "Lasbela" },
  { value: "Layyah" },
  { value: "Loralai" },
  { value: "Lower Chitral" },
  { value: "Lower Dir" },
  { value: "Lower Kohistan" },
  { value: "Malakand" },
  { value: "Malir" },
  { value: "Mandi Bahauddin" },
  { value: "Bhimber" },
  { value: "Buner" },
  { value: "Chagai" },
  { value: "Chakwal" },
  { value: "Charsadda" },
  { value: "Chiniot" },
  { value: "Dadu" },
  { value: "Darel" },
  { value: "Dera Bugti" },
  { value: "Dera Ghazi Khan" },
  { value: "Dera Ismail Khan" },
  { value: "Diamer" },
  { value: "Duki" },
  { value: "Faisalabad" },
  { value: "Ghanche" },
  { value: "Ghizer" },
  { value: "Ghotki" },
  { value: "Gilgit" },
  { value: "Gujranwala" },
  { value: "Gujrat" },
  { value: "Gupis Yasin" },
  { value: "Gwadar" },
  { value: "Hafizabad" },
  { value: "Hangu" },
  { value: "Haripur" },
  { value: "Harnai" },
  { value: "Hattian" },
  { value: "Haveli" },
  { value: "Hunza" },
  { value: "Hyderabad" },
  { value: "Islamabad" },
  { value: "Jacobabad" },
  { value: "Jafarabad" },
  { value: "Jamshoro" },
  { value: "Jhal Magsi" },
  { value: "Jhang" },
  { value: "Jhelum" },
  { value: "Kachhi" },
  { value: "Kalat" },
  { value: "Karachi Central" },
  { value: "Karachi East" },
  { value: "Karachi South" },
  { value: "Karachi West" },
  { value: "Karak" },
  { value: "Kashmore" },
  { value: "Kasur" },
  { value: "Kech" },
  { value: "Khairpur" },
  { value: "Khanewal" },
  { value: "Kharan" },
  { value: "Kharmang" },
  { value: "Khushab" },
  { value: "Khuzdar" },
  { value: "Khyber" },
  { value: "Killa Abdullah" },
  { value: "Kohat" },
  { value: "Kohlu" },
  { value: "Kolai Pallas" },
  { value: "Korangi" },
  { value: "Kotli" },
  { value: "Kurram" },
  { value: "Lahore" },
  { value: "Lakki Marwat" },
  { value: "Larkana" },
  { value: "Lasbela" },
  { value: "Layyah" },
  { value: "Loralai" },
  { value: "Lower Chitral" },
  { value: "Lower Dir" },
  { value: "Lower Kohistan" },
  { value: "Malakand" },
  { value: "Malir" },
  { value: "Mandi Bahauddin" },
  { value: "Mansehra" },
  { value: "Mardan" },
  { value: "Mastung" },
  { value: "Matiari" },
  { value: "Mianwali" },
  { value: "Mirpur Khas" },
  { value: "Mirpur" },
  { value: "Mohmand" },
  { value: "Multan" },
  { value: "Musakhel" },
  { value: "Muzaffarabad" },
  { value: "Muzaffargarh" },
  { value: "Nagar" },
  { value: "Nankana Sahib" },
  { value: "Narowal" },
  { value: "Naseerabad" },
  { value: "Naushahro Firoze" },
  { value: "Neelum" },
  { value: "North Waziristan" },
  { value: "Nowshera" },
  { value: "Nushki" },
  { value: "Okara" },
  { value: "Orakzai" },
  { value: "Pakpattan" },
  { value: "Panjgur" },
  { value: "Peshawar" },
  { value: "Pishin" },
  { value: "Poonch" },
  { value: "Qambar Shahdadkot" },
  { value: "Qilla Saifullah" },
  { value: "Quetta" },
  { value: "Rahim Yar Khan" },
  { value: "Rajanpur" },
  { value: "Rawalpindi" },
  { value: "Roundu" },
  { value: "Sahiwal" },
  { value: "Sanghar" },
  { value: "Sargodha" },
  { value: "Shaheed Benazirabad" },
  { value: "Shaheed Sikandarabad" },
  { value: "Shangla" },
  { value: "Sheikhupura" },
  { value: "Sherani" },
  { value: "Shigar" },
  { value: "Shikarpur" },
  { value: "Sialkot" },
  { value: "Sibi" },
  { value: "Skardu" },
  { value: "Sohbatpur" },
  { value: "South Waziristan" },
  { value: "Sudhnutti" },
  { value: "Sujawal" },
  { value: "Sukkur" },
  { value: "Swabi" },
  { value: "Swat" },
  { value: "Tando Allahyar" },
  { value: "Tando Muhammad Khan" },
  { value: "Tangir" },
  { value: "Tank" },
  { value: "Tharparkar" },
  { value: "Thatta" },
  { value: "Toba Tek Singh" },
  { value: "Tor Ghar" },
  { value: "Umerkot" },
  { value: "Upper Chitral" },
  { value: "Upper Dir" },
  { value: "Upper Kohistan" },
  { value: "Vehari" },
  { value: "Washuk" },
  { value: "Zhob" },
  { value: "Ziarat" },
];

export const eventsList = [
  {
    id: 1,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque eveniet iure sit harum iste. Commodi libero tenetur error itaque obcaecati cum neque. Praesentium impedit minima doloremque asperiores ipsam cum perferendis cumque rem natus omnis eum officiis adipisci, laudantium voluptatibus dignissimos sapiente mollitia ullam obcaecati harum quos accusamus? A vitae doloremque laborum doloribus omnis culpa quaerat illo cumque dolore quia repudiandae, repellendus magni, ipsum assumenda provident laudantium eum impedit. Voluptas eveniet deleniti veniam hic culpa iure at placeat facere voluptatum beatae? Commodi deleniti tenetur quo a, aperiam ratione iure, numquam, minus optio odit non molestias? Fugiat culpa sint delectus inventore quo explicabo aliquam error natus quisquam odit ad, officiis sunt repudiandae aliquid consequuntur, harum ipsum, tempore reiciendis eligendi! Illo ratione eum ullam earum dicta quo nemo harum exercitationem, modi ab a perspiciatis obcaecati deserunt atque necessitatibus at odio numquam perferendis consequatur. Molestiae accusamus molestias veniam facere excepturi possimus nam aliquam veritatis at eligendi consequuntur autem deserunt illo debitis ad corrupti repellendus officiis, neque optio laborum hic aspernatur pariatur! Sit explicabo quis ducimus enim? Error, modi id? Officia quasi ipsa ducimus, eaque minima nisi accusantium tenetur, voluptates ad, tempore non consequatur et nostrum ab earum quidem veritatis impedit voluptate odio quos saepe.",
    date: "13 Jul 2020",
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/2123755/pexels-photo-2123755.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
    title: "Conquer the World",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/1576937/pexels-photo-1576937.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;w=500",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
];
