// nav list component
export const navListItems = [
  {
    label: "Home",
    location: "/",
  },
  {
    label: "About",
    location: "/about",
  },
  {
    label: "Find Donor",
    location: "/find-donor",
  },
  {
    label: "Donate",
    location: "/donate",
  },
  {
    label: "Get Help",
    location: "/get-help",
  },
  {
    label: "Login",
    location: "/donor/login",
  },
];

export const cities = [
  { value: "abbottabad", label: "Abbottabad" },
  { value: "astore", label: "Astore" },
  { value: "attock", label: "Attock" },
  { value: "awaran", label: "Awaran" },
  { value: "badin", label: "Badin" },
  { value: "bagh", label: "Bagh" },
  { value: "bahawalnagar", label: "Bahawalnagar" },
  { value: "bahawalpur", label: "Bahawalpur" },
  { value: "bajaur", label: "Bajaur" },
  { value: "bannu", label: "Bannu" },
  { value: "barkhan", label: "Barkhan" },
  { value: "bhimber", label: "Bhimber" },
  { value: "buner", label: "Buner" },
  { value: "chagai", label: "Chagai" },
  { value: "chakwal", label: "Chakwal" },
  { value: "charsadda", label: "Charsadda" },
  { value: "chiniot", label: "Chiniot" },
  { value: "dadu", label: "Dadu" },
  { value: "darel", label: "Darel" },
  { value: "dera bugti", label: "Dera Bugti" },
  { value: "dera ghazi khan", label: "Dera Ghazi Khan" },
  { value: "dera ismail khan", label: "Dera Ismail Khan" },
  { value: "diamer", label: "Diamer" },
  { value: "duki", label: "Duki" },
  { value: "faisalabad", label: "Faisalabad" },
  { value: "ghanche", label: "Ghanche" },
  { value: "ghizer", label: "Ghizer" },
  { value: "ghotki", label: "Ghotki" },
  { value: "gilgit", label: "Gilgit" },
  { value: "gujranwala", label: "Gujranwala" },
  { value: "gujrat", label: "Gujrat" },
  { value: "gupis yasin", label: "Gupis Yasin" },
  { value: "gwadar", label: "Gwadar" },
  { value: "hafizabad", label: "Hafizabad" },
  { value: "hangu", label: "Hangu" },
  { value: "haripur", label: "Haripur" },
  { value: "harnai", label: "Harnai" },
  { value: "hattian", label: "Hattian" },
  { value: "haveli", label: "Haveli" },
  { value: "hunza", label: "Hunza" },
  { value: "hyderabad", label: "Hyderabad" },
  { value: "islamabad", label: "Islamabad" },
  { value: "jacobabad", label: "Jacobabad" },
  { value: "jafarabad", label: "Jafarabad" },
  { value: "jamshoro", label: "Jamshoro" },
  { value: "jhal magsi", label: "Jhal Magsi" },
  { value: "jhang", label: "Jhang" },
  { value: "jhelum", label: "Jhelum" },
  { value: "kachhi", label: "Kachhi" },
  { value: "kalat", label: "Kalat" },
  { value: "karachi central", label: "Karachi Central" },
  { value: "karachi east", label: "Karachi East" },
  { value: "karachi south", label: "Karachi South" },
  { value: "karachi west", label: "Karachi West" },
  { value: "karak", label: "Karak" },
  { value: "kashmore", label: "Kashmore" },
  { value: "kasur", label: "Kasur" },
  { value: "kech", label: "Kech" },
  { value: "khairpur", label: "Khairpur" },
  { value: "khanewal", label: "Khanewal" },
  { value: "kharan", label: "Kharan" },
  { value: "kharmang", label: "Kharmang" },
  { value: "khushab", label: "Khushab" },
  { value: "khuzdar", label: "Khuzdar" },
  { value: "khyber", label: "Khyber" },
  { value: "killa abdullah", label: "Killa Abdullah" },
  { value: "kohat", label: "Kohat" },
  { value: "kohlu", label: "Kohlu" },
  { value: "kolai pallas", label: "Kolai Pallas" },
  { value: "korangi", label: "Korangi" },
  { value: "kotli", label: "Kotli" },
  { value: "kurram", label: "Kurram" },
  { value: "lahore", label: "Lahore" },
  { value: "lakki marwat", label: "Lakki Marwat" },
  { value: "larkana", label: "Larkana" },
  { value: "lasbela", label: "Lasbela" },
  { value: "layyah", label: "Layyah" },
  { value: "loralai", label: "Loralai" },
  { value: "lower chitral", label: "Lower Chitral" },
  { value: "lower dir", label: "Lower Dir" },
  { value: "lower kohistan", label: "Lower Kohistan" },
  { value: "malakand", label: "Malakand" },
  { value: "malir", label: "Malir" },
  { value: "mandi bahauddin", label: "Mandi Bahauddin" },
  { value: "mansehra", label: "Mansehra" },
  { value: "mardan", label: "Mardan" },
  { value: "mastung", label: "Mastung" },
  { value: "matiari", label: "Matiari" },
  { value: "mianwali", label: "Mianwali" },
  { value: "mirpur khas", label: "Mirpur Khas" },
  { value: "mirpur", label: "Mirpur" },
  { value: "mohmand", label: "Mohmand" },
  { value: "multan", label: "Multan" },
  { value: "musakhel", label: "Musakhel" },
  { value: "muzaffarabad", label: "Muzaffarabad" },
  { value: "muzaffargarh", label: "Muzaffargarh" },
  { value: "nagar", label: "Nagar" },
  { value: "nankana sahib", label: "Nankana Sahib" },
  { value: "narowal", label: "Narowal" },
  { value: "naseerabad", label: "Naseerabad" },
  { value: "naushahro firoze", label: "Naushahro Firoze" },
  { value: "neelum", label: "Neelum" },
  { value: "north waziristan", label: "North Waziristan" },
  { value: "nowshera", label: "Nowshera" },
  { value: "nushki", label: "Nushki" },
  { value: "okara", label: "Okara" },
  { value: "orakzai", label: "Orakzai" },
  { value: "pakpattan", label: "Pakpattan" },
  { value: "panjgur", label: "Panjgur" },
  { value: "peshawar", label: "Peshawar" },
  { value: "pishin", label: "Pishin" },
  { value: "poonch", label: "Poonch" },
  { value: "qambar shahdadkot", label: "Qambar Shahdadkot" },
  { value: "qilla saifullah", label: "Qilla Saifullah" },
  { value: "quetta", label: "Quetta" },
  { value: "rahim yar khan", label: "Rahim Yar Khan" },
  { value: "rajanpur", label: "Rajanpur" },
  { value: "rawalpindi", label: "Rawalpindi" },
  { value: "roundu", label: "Roundu" },
  { value: "sahiwal", label: "Sahiwal" },
  { value: "sanghar", label: "Sanghar" },
  { value: "sargodha", label: "Sargodha" },
  { value: "shaheed benazirabad", label: "Shaheed Benazirabad" },
  { value: "shaheed sikandarabad", label: "Shaheed Sikandarabad" },
  { value: "shangla", label: "Shangla" },
  { value: "sheikhupura", label: "Sheikhupura" },
  { value: "sherani", label: "Sherani" },
  { value: "shigar", label: "Shigar" },
  { value: "shikarpur", label: "Shikarpur" },
  { value: "sialkot", label: "Sialkot" },
  { value: "sibi", label: "Sibi" },
  { value: "skardu", label: "Skardu" },
  { value: "sohbatpur", label: "Sohbatpur" },
  { value: "south waziristan", label: "South Waziristan" },
  { value: "sudhnutti", label: "Sudhnutti" },
  { value: "sujawal", label: "Sujawal" },
  { value: "sukkur", label: "Sukkur" },
  { value: "swabi", label: "Swabi" },
  { value: "swat", label: "Swat" },
  { value: "tando allahyar", label: "Tando Allahyar" },
  { value: "tando muhammad khan", label: "Tando Muhammad Khan" },
  { value: "tangir", label: "Tangir" },
  { value: "tank", label: "Tank" },
  { value: "tharparkar", label: "Tharparkar" },
  { value: "thatta", label: "Thatta" },
  { value: "toba tek singh", label: "Toba Tek Singh" },
  { value: "tor ghar", label: "Tor Ghar" },
  { value: "umerkot", label: "Umerkot" },
  { value: "upper chitral", label: "Upper Chitral" },
  { value: "upper dir", label: "Upper Dir" },
  { value: "upper kohistan", label: "Upper Kohistan" },
  { value: "vehari", label: "Vehari" },
  { value: "washuk", label: "Washuk" },
  { value: "zhob", label: "Zhob" },
  { value: "ziarat", label: "Ziarat" },
];

export const bloodGroups = [
  { label: "A+", value: "a-p" },
  { label: "A-", value: "a-n" },
  { label: "B+", value: "b-p" },
  { label: "B-", value: "b-n" },
  { label: "AB+", value: "ab-p" },
  { label: "AB-", value: "ab-n" },
  { label: "O+", value: "o-p" },
  { label: "O-", value: "o-n" },
];

export const eventsList = [
  {
    id: 1,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque eveniet iure sit harum iste. Commodi libero tenetur error itaque obcaecati cum neque. Praesentium impedit minima doloremque asperiores ipsam cum perferendis cumque rem natus omnis eum officiis adipisci, laudantium voluptatibus dignissimos sapiente mollitia ullam obcaecati harum quos accusamus? A vitae doloremque laborum doloribus omnis culpa quaerat illo cumque dolore quia repudiandae, repellendus magni, ipsum assumenda provident laudantium eum impedit. Voluptas eveniet deleniti veniam hic culpa iure at placeat facere voluptatum beatae? Commodi deleniti tenetur quo a, aperiam ratione iure, numquam, minus optio odit non molestias? Fugiat culpa sint delectus inventore quo explicabo aliquam error natus quisquam odit ad, officiis sunt repudiandae aliquid consequuntur, harum ipsum, tempore reiciendis eligendi! Illo ratione eum ullam earum dicta quo nemo harum exercitationem, modi ab a perspiciatis obcaecati deserunt atque necessitatibus at odio numquam perferendis consequatur. Molestiae accusamus molestias veniam facere excepturi possimus nam aliquam veritatis at eligendi consequuntur autem deserunt illo debitis ad corrupti repellendus officiis, neque optio laborum hic aspernatur pariatur! Sit explicabo quis ducimus enim? Error, modi id? Officia quasi ipsa ducimus, eaque minima nisi accusantium tenetur, voluptates ad, tempore non consequatur et nostrum ab earum quidem veritatis impedit voluptate odio quos saepe.",
    date: "13 Jul 2020",
  },
  {
    id: 2,
    image: "https://images.pexels.com/photos/2123755/pexels-photo-2123755.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;h=750&amp;w=1260",
    title: "Conquer the World",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 3,
    image: "https://images.pexels.com/photos/1576937/pexels-photo-1576937.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=2&amp;w=500",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 4,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 5,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 6,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 7,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 8,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
  {
    id: 9,
    image: "https://images.pexels.com/photos/932638/pexels-photo-932638.jpeg?auto=compress&amp;cs=tinysrgb&amp;dpr=3&amp;h=750&amp;w=1260",
    title: "Diving to the deep",
    short_desc: "Sed ut perspiciatis unde omnis iste natus error sit sed quia consequuntur magni voluptatem doloremque.",
    full_desc: "",
    date: "13 Jul 2020",
  },
];

export const getBloodGroupRepresentation = (value) => {
  const bloodGroups = {
    "a-p": "A+",
    "a-n": "A-",
    "b-p": "B+",
    "b-n": "B-",
    "ab-p": "AB+",
    "ab-n": "AB-",
    "o-p": "O+",
    "o-n": "O-",
  };

  return bloodGroups[value] || "";
};
